Table marque {
  id_marque int [pk, increment]
  nom_marque varchar
}

Table os {
  id_os int [pk, increment]
  nom_os varchar
}

Table software {
  id_software int [pk, increment]
  nom_software varchar
}

Table software_installe {
  id_software_installe int [pk, increment]
  software_id int
  pc_id int
  foreign key [software_id] references software[id_software]
  foreign key [pc_id] references PC[id]
}

Table PC {
  id int [pk, increment]
  marque_id int
  date_achat date
  ram int
  user varchar
  dd_size int
  foreign key [marque_id] references marque[id_marque]
}

Table technicien {
  id_technicien int [pk, increment]
  nom_technicien varchar
}

