TAble marque {
 id_marque [pk, increment]
 nom_marque varchar 
} 

TAble os {
 id_os [pk, increment]
 nom_os varchar 
} 

TAble software {
 id_software [pk, increment]
 nom_software varchar 
} 

TAble software_installe {
 id_software_installe [pk, increment]
 nom_software varchar 
} 

TAble PC  {
 id int [pk, increment]
 marque_id varchar 
 date_achat date
 ram int
 user varchar
 dd_size int
} 

TAble technicien{
 id_technicien [pk, increment]
 nom_technicien varchar
} 
 
