CREATE TABLE "marque" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom_marque" varchar(200)
);

CREATE TABLE "os" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom_os" varchar(200)
);

CREATE TABLE "software" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom_software" varchar(200)
);

CREATE TABLE "software_installe" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom_software" varchar(200)
);

CREATE TABLE "PC" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "marque_id" varchar(200),
  "date_achat" date,
  "ram" int,
  "user" varchar,
  "dd_size" int
);

CREATE TABLE "technicien" (
  "id_technicien" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nom_technicien" varchar(200)
);

