Vagrant.configure("2") do |config|

  config.vm.define "machine1" do |machine1|
    machine1.vm.box = "generic/ubuntu2004"
    machine1.vm.network "private_network", ip: "10.10.20.3"
	machine1.vm.provider :libvirt do |libvirt|
		libvirt.memory = 4096
		libvirt.cpus = 2
  end

	machine1.ssh.username = "vagrant"
	machine1.ssh.insert_key = false
 end

  config.vm.define "machine2" do |machine2|
    machine2.vm.box = "generic/ubuntu2004"
    machine2.vm.network "private_network", ip: "10.10.20.4"
	machine2.vm.provider :libvirt do |libvirt|
		libvirt.memory = 1024
		libvirt.cpus = 1
  end
	
	machine2.ssh.username = "vagrant"
	machine2.ssh.insert_key = false
 end

  config.vm.define "machine3" do |machine3|
    machine3.vm.box = "generic/ubuntu2004"
    machine3.vm.network "private_network", ip: "10.10.20.5"
	machine3.vm.provider :libvirt do |libvirt|
		libvirt.memory = 1024
		libvirt.cpus = 1
  end
	machine3.ssh.username = "vagrant"
	machine3.ssh.insert_key = false
 end

end
